version: 2

models:
  - name: stg_customers
    description: "Staged customers"
    columns:
      - name: customer_id
        tests: [not_null]
      - name: signup_date
      - name: country

  - name: stg_orders
    description: "Staged orders"
    columns:
      - name: order_id
        tests: [not_null]
      - name: customer_id
      - name: order_date
      - name: status
      - name: total_amount
